name: Auto Deploy to Windows PC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Trigger Deployment Script
        # 러너가 기본적으로 PowerShell을 사용하므로 cmd를 명시하여 실행합니다.
        run: |
          cd "C:\Users\s525h\git_repo\project_poc"
          cmd /c deploy.bat
